#!/usr/bin/env python3
# Copyright 2020 The Chromium OS Authors. All rights reserved.
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

"""Wrapper around repo to auto-update depot_tools during sync.

gclient keeps depot_tools up-to-date automatically for Chromium developers.

We only want to do this on `repo sync` operations as that implies a network
operation, and update_depot_tools is not cheap.
"""

import os
from pathlib import Path
import subprocess
import sys


# Some useful paths.
DEPOT_TOOLS_DIR = Path(__file__).resolve().parent
UPDATE_DEPOT_TOOLS = DEPOT_TOOLS_DIR / 'update_depot_tools'
REPO = DEPOT_TOOLS_DIR / 'repo_launcher'

def main(argv):
  # This is a bit hacky, but should be "good enough".  If repo itself gains
  # support for sync hooks, we could switch to that.
  if argv and argv[0] == 'sync':
    _UpdateDepotTools()

  os.execv(sys.executable, [sys.executable, str(REPO)] + argv)


if __name__ == '__main__':
  sys.exit(main(sys.argv[1:]))
